- src/main/java/br/com/mercadolivre/desafiospring/models/Product.java
- Create a model for product class.
close #1
> feat: add product model

- .gitmessage
- src/main/java/br/com/mercadolivre/desafiospring/repository/ApplicationRepository.java
- src/main/java/br/com/mercadolivre/desafiospring/services/ProductService.java
Add product service.
closes #3
> feat: add product service

- src/main/java/br/com/mercadolivre/desafiospring/controller/ProductController.java
- src/main/java/br/com/mercadolivre/desafiospring/dto/request/ProductDTO.java
Add new route for products insertion, create new files for DTO on products.
API - OK
> feat: add insert product route

- src/main/java/br/com/mercadolivre/desafiospring/controller/ClientController.java
Implements a controller for a future client model
close #19
> feat: add client controller

- src/main/java/br/com/mercadolivre/desafiospring/controller/PurchaseController.java
- src/main/java/br/com/mercadolivre/desafiospring/dto/request/PurchaseDTO.java
- src/main/java/br/com/mercadolivre/desafiospring/models/Purchase.java
- src/main/java/br/com/mercadolivre/desafiospring/services/PurchaseService.java
Add model for purchase action and create endpoint on postman service.
closed : #15
> feat: create purchase model

- src/main/java/br/com/mercadolivre/desafiospring/dto/request/AddressDTO.java
- src/main/java/br/com/mercadolivre/desafiospring/dto/request/ClientDTO.java
- src/main/java/br/com/mercadolivre/desafiospring/models/Address.java
- src/main/java/br/com/mercadolivre/desafiospring/models/Client.java
- src/main/java/br/com/mercadolivre/desafiospring/services/ClientValidator.java
Including Model and DTO for Client and their address, and also, creating a email validation for client. for future use
close: #14
> Add Client model

- README.md
Melhora a apresentação do README.md
> melhorando readme.md

- src/main/java/br/com/mercadolivre/desafiospring/services/ClientService.java
> Feat add client service

- src/main/java/br/com/mercadolivre/desafiospring/services/ProductService.java
- src/main/java/br/com/mercadolivre/desafiospring/strategies/PriceSort.java
using strategy pattern implemented in #35 , add both highest to lower and lower to highest price sorting. 
teste here [POSTMAN](https://galactic-satellite-194316.postman.co/workspace/W5G6---Java-Lee~da556dc7-51a0-4d90-9b1a-74d7a2c4c7a6/request/20170672-b8c5bc1a-5157-43d1-b51b-c9afaeb22902)
or with `sh`
```zsh
curl -X GET 'localhost:8080/api/v1/articles?order=2'
curl -X GET 'localhost:8080/api/v1/articles?order=3'
```
products used to test:
```JSON
{
"products": [
{
"productId":1,
"name":"Serra de Bancada",
"category":"Ferramentas",
"brand":"FORTGPRO",
"price":1800.00,
"quantity":5,
"freeShipping":true,
"prestige":"****"
},
{
"productId":2,
"name":"Furadeira",
"category":"Ferramentas",
"brand":"Black & Decker",
"price":500.00,
"quantity":7,
"freeShipping":true,
"prestige":"****"
},
{ …
```
> feat: add price sort

- README.md
Improvement of README that explains each application layer
doc
> doc: add description of app structure

- src/main/java/br/com/mercadolivre/desafiospring/controller/ClientController.java
- src/main/java/br/com/mercadolivre/desafiospring/services/ClientService.java
Also create an endpoint to create clients, just to test the list endpoint.
close #20
> feat: add end point to list clients

- src/main/java/br/com/mercadolivre/desafiospring/controller/ProductController.java
- src/main/java/br/com/mercadolivre/desafiospring/services/ProductService.java
-add filter by category
close #9
> feat: filter by category

- src/main/java/br/com/mercadolivre/desafiospring/database/clients.json
- src/main/java/br/com/mercadolivre/desafiospring/models/Address.java
- src/main/java/br/com/mercadolivre/desafiospring/models/Client.java
- src/main/java/br/com/mercadolivre/desafiospring/repository/ApplicationRepository.java
- src/main/java/br/com/mercadolivre/desafiospring/repository/ClientRepository.java
- src/main/java/br/com/mercadolivre/desafiospring/repository/ProductRepository.java
- src/main/java/br/com/mercadolivre/desafiospring/utils/ClassUtils.java
Add Client repository
Usage of findBy method
You can filter by any field from class and any field from the first level of dependency.
e.g.
class Client attributes
```
public class Client {
private Long id;
private String name;
private String email;
private Address address;
}
```
You can filter from any field from Client (id, name, email) and from first level of dependency (Address (uf, street, etc..)).
Call using passing a map:
```
findBy(Map.of("name", "clientName", "address.uf", "SP"));
```
NOTE: If address has another dependency, the filter will not work to the lower levels, e.g
Consider another dependency inside address class and using the same Client class from above.
```
public class Address {
private String street;
private String UF;
private PostalCodeClass postalCode;
}
```
I …
> feat: add client repository

- src/main/java/br/com/mercadolivre/desafiospring/controller/PurchaseController.java
- src/main/java/br/com/mercadolivre/desafiospring/database/purchases.json
- src/main/java/br/com/mercadolivre/desafiospring/dto/request/PurchaseDTO.java
- src/main/java/br/com/mercadolivre/desafiospring/dto/request/PurchaseRequestDTO.java
- src/main/java/br/com/mercadolivre/desafiospring/models/Purchase.java
- src/main/java/br/com/mercadolivre/desafiospring/models/PurchaseRequest.java
- src/main/java/br/com/mercadolivre/desafiospring/repository/PurchaseRepository.java
- src/main/java/br/com/mercadolivre/desafiospring/services/PurchaseService.java
Create service for purchase action, and db purchase transactions 
- depends on #15
closed : #16 #17 #23
> feat: create db for purchase and add services propiets

- src/main/java/br/com/mercadolivre/desafiospring/repository/PurchaseRepository.java
Implementing missing methods
fix #23
> Implementing missing methods from purchase repository

- src/main/java/br/com/mercadolivre/desafiospring/controller/ProductController.java
- src/main/java/br/com/mercadolivre/desafiospring/services/ProductService.java
Create a get method that fetch products from the file (database).
closed #7
closed #8
> feat: create get method

- src/main/java/br/com/mercadolivre/desafiospring/controller/ProductController.java
- src/main/java/br/com/mercadolivre/desafiospring/database/products.json
> refact: changing end point to create product

- src/main/java/br/com/mercadolivre/desafiospring/database/FileManager.java
- src/main/java/br/com/mercadolivre/desafiospring/repository/ProductRepository.java
- src/main/java/br/com/mercadolivre/desafiospring/repository/PurchaseRepository.java
- src/main/resources/application.properties
Add on application properties the path of json archives as env variable
> feat: add local env variable to path of archives jsons

- src/main/java/br/com/mercadolivre/desafiospring/controller/PurchaseController.java
- src/main/java/br/com/mercadolivre/desafiospring/dto/request/CartDTO.java
- src/main/java/br/com/mercadolivre/desafiospring/repository/PurchaseRepository.java
- src/main/java/br/com/mercadolivre/desafiospring/services/PurchaseService.java
> feat: add a new route that sum the price of all customer products

- src/main/java/br/com/mercadolivre/desafiospring/dto/request/PurchaseDTO.java
- src/main/java/br/com/mercadolivre/desafiospring/models/Purchase.java
- src/main/java/br/com/mercadolivre/desafiospring/repository/PurchaseRepository.java
- src/main/java/br/com/mercadolivre/desafiospring/services/PurchaseService.java
> fix: change customerId from Purchase class from int to Long

- src/main/java/br/com/mercadolivre/desafiospring/controller/advice/DBExceptionHandler.java
- src/main/java/br/com/mercadolivre/desafiospring/exceptions/db/DataBaseReadException.java
- src/main/java/br/com/mercadolivre/desafiospring/exceptions/db/DataBaseWriteException.java
changes on "throws" will be implemented later
start #39
> feat: creating a RestControllerAdvice to handle DB exceptions

- src/main/java/br/com/mercadolivre/desafiospring/controller/advice/DBExceptionHandler.java
- src/main/java/br/com/mercadolivre/desafiospring/database/FileManager.java
> fix: fixing blank errors mesage

- src/main/java/br/com/mercadolivre/desafiospring/controller/PurchaseController.java
- src/main/java/br/com/mercadolivre/desafiospring/dto/request/CartDTO.java
- src/main/java/br/com/mercadolivre/desafiospring/services/PurchaseService.java
> fix: adjustment of cart total price

- src/main/java/br/com/mercadolivre/desafiospring/repository/ProductRepository.java
- src/main/java/br/com/mercadolivre/desafiospring/repository/PurchaseRepository.java
- src/main/java/br/com/mercadolivre/desafiospring/services/CustomerService.java
- src/main/java/br/com/mercadolivre/desafiospring/validators/AddressValidator.java
> Hotfix customer creation

- src/main/java/br/com/mercadolivre/desafiospring/controller/CustomerController.java
- src/main/java/br/com/mercadolivre/desafiospring/dto/request/PurchaseRequestDTO.java
- src/main/java/br/com/mercadolivre/desafiospring/models/PurchaseRequest.java
- src/main/java/br/com/mercadolivre/desafiospring/repository/ApplicationRepository.java
- src/main/java/br/com/mercadolivre/desafiospring/repository/ProductRepository.java
- src/main/java/br/com/mercadolivre/desafiospring/services/CustomerService.java
- src/main/java/br/com/mercadolivre/desafiospring/services/ProductService.java
- src/main/java/br/com/mercadolivre/desafiospring/services/PurchaseOperation.java
- src/main/java/br/com/mercadolivre/desafiospring/services/PurchaseService.java
create purchase operation, convert new purchase requisition as a new purchase. 
calc the total price for a new request purchase, and add new TODO list for refactoring the errors handlers 
Closed #49
> Feat add convert purchase request to purchase

- src/main/java/br/com/mercadolivre/desafiospring/controller/ProductController.java
- src/main/java/br/com/mercadolivre/desafiospring/dto/response/ResponseFilterDTO.java
> feat: add dto response to filter product controller

- src/main/java/br/com/mercadolivre/desafiospring/controller/PurchaseController.java
> fix: add purchases existing validation on effective cart operation

- README.md
> doc: add some information about the layer structure
